# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values
# __do not exceed four million__, find the sum of the even-valued terms.

def produce_fibs(under=100):
    a = b = 1
    while a < under:
        yield a
        a, b = b, a + b


print(list(produce_fibs()))
